Date.dayNames="Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(",");Date.abbrDayNames="Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(",");Date.monthNames="January,February,March,April,May,June,July,August,September,October,November,December".split(",");Date.abbrMonthNames="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(",");Date.firstDayOfWeek=1;Date.format="dd/mm/yyyy";Date.fullYearStart="20";
(function(){function a(a,g){Date.prototype[a]||(Date.prototype[a]=g)}a("isLeapYear",function(){var a=this.getFullYear();return a%4==0&&a%100!=0||a%400==0});a("isWeekend",function(){return this.getDay()==0||this.getDay()==6});a("isWeekDay",function(){return!this.isWeekend()});a("getDaysInMonth",function(){return[31,this.isLeapYear()?29:28,31,30,31,30,31,31,30,31,30,31][this.getMonth()]});a("getDayName",function(a){return a?Date.abbrDayNames[this.getDay()]:Date.dayNames[this.getDay()]});a("getMonthName",
function(a){return a?Date.abbrMonthNames[this.getMonth()]:Date.monthNames[this.getMonth()]});a("getDayOfYear",function(){var a=new Date("1/1/"+this.getFullYear());return Math.floor((this.getTime()-a.getTime())/864E5)});a("getWeekOfYear",function(){return Math.ceil(this.getDayOfYear()/7)});a("setDayOfYear",function(a){this.setMonth(0);this.setDate(a);return this});a("addYears",function(a){this.setFullYear(this.getFullYear()+a);return this});a("addMonths",function(a){var g=this.getDate();this.setMonth(this.getMonth()+
a);g>this.getDate()&&this.addDays(-this.getDate());return this});a("addDays",function(a){this.setTime(this.getTime()+a*864E5);return this});a("addHours",function(a){this.setHours(this.getHours()+a);return this});a("addMinutes",function(a){this.setMinutes(this.getMinutes()+a);return this});a("addSeconds",function(a){this.setSeconds(this.getSeconds()+a);return this});a("zeroTime",function(){this.setMilliseconds(0);this.setSeconds(0);this.setMinutes(0);this.setHours(0);return this});a("asString",function(a){return(a||
Date.format).split("yyyy").join(this.getFullYear()).split("yy").join((this.getFullYear()+"").substring(2)).split("mmmm").join(this.getMonthName(false)).split("mmm").join(this.getMonthName(true)).split("mm").join(c(this.getMonth()+1)).split("dd").join(c(this.getDate())).split("hh").join(c(this.getHours())).split("min").join(c(this.getMinutes())).split("ss").join(c(this.getSeconds()))});Date.fromString=function(a,g){var d=g||Date.format,e=new Date("01/01/1977"),c=0,f=d.indexOf("mmmm");if(f>-1){for(var b=
0;b<Date.monthNames.length;b++){var j=a.substr(f,Date.monthNames[b].length);if(Date.monthNames[b]==j){c=Date.monthNames[b].length-4;break}}e.setMonth(b)}else if(f=d.indexOf("mmm"),f>-1){j=a.substr(f,3);for(b=0;b<Date.abbrMonthNames.length;b++)if(Date.abbrMonthNames[b]==j)break;e.setMonth(b)}else e.setMonth(Number(a.substr(d.indexOf("mm"),2))-1);b=d.indexOf("yyyy");b>-1?(f<b&&(b+=c),e.setFullYear(Number(a.substr(b,4)))):e.setFullYear(Number(Date.fullYearStart+a.substr(d.indexOf("yy"),2)));d=d.indexOf("dd");
f<d&&(d+=c);e.setDate(Number(a.substr(d,2)));return isNaN(e.getTime())?false:e};var c=function(a){a="0"+a;return a.substring(a.length-2)}})();Date.dayNames="Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(",");Date.abbrDayNames="Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(",");Date.monthNames="January,February,March,April,May,June,July,August,September,October,November,December".split(",");Date.abbrMonthNames="Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec".split(",");
Date.firstDayOfWeek=1;Date.format="dd/mm/yyyy";Date.fullYearStart="20";
(function(){function a(a,c){Date.prototype[a]||(Date.prototype[a]=c)}a("isLeapYear",function(){var a=this.getFullYear();return a%4==0&&a%100!=0||a%400==0});a("isWeekend",function(){return this.getDay()==0||this.getDay()==6});a("isWeekDay",function(){return!this.isWeekend()});a("getDaysInMonth",function(){return[31,this.isLeapYear()?29:28,31,30,31,30,31,31,30,31,30,31][this.getMonth()]});a("getDayName",function(a){return a?Date.abbrDayNames[this.getDay()]:Date.dayNames[this.getDay()]});a("getMonthName",
function(a){return a?Date.abbrMonthNames[this.getMonth()]:Date.monthNames[this.getMonth()]});a("getDayOfYear",function(){var a=new Date("1/1/"+this.getFullYear());return Math.floor((this.getTime()-a.getTime())/864E5)});a("getWeekOfYear",function(){return Math.ceil(this.getDayOfYear()/7)});a("setDayOfYear",function(a){this.setMonth(0);this.setDate(a);return this});a("addYears",function(a){this.setFullYear(this.getFullYear()+a);return this});a("addMonths",function(a){var c=this.getDate();this.setMonth(this.getMonth()+
a);c>this.getDate()&&this.addDays(-this.getDate());return this});a("addDays",function(a){this.setTime(this.getTime()+a*864E5);return this});a("addHours",function(a){this.setHours(this.getHours()+a);return this});a("addMinutes",function(a){this.setMinutes(this.getMinutes()+a);return this});a("addSeconds",function(a){this.setSeconds(this.getSeconds()+a);return this});a("zeroTime",function(){this.setMilliseconds(0);this.setSeconds(0);this.setMinutes(0);this.setHours(0);return this});a("asString",function(a){return(a||
Date.format).split("yyyy").join(this.getFullYear()).split("yy").join((this.getFullYear()+"").substring(2)).split("mmmm").join(this.getMonthName(false)).split("mmm").join(this.getMonthName(true)).split("mm").join(c(this.getMonth()+1)).split("dd").join(c(this.getDate())).split("hh").join(c(this.getHours())).split("min").join(c(this.getMinutes())).split("ss").join(c(this.getSeconds()))});Date.fromString=function(a,c){var d=c||Date.format,e=new Date("01/01/1977"),h=0,f=d.indexOf("mmmm");if(f>-1){for(var b=
0;b<Date.monthNames.length;b++){var j=a.substr(f,Date.monthNames[b].length);if(Date.monthNames[b]==j){h=Date.monthNames[b].length-4;break}}e.setMonth(b)}else if(f=d.indexOf("mmm"),f>-1){j=a.substr(f,3);for(b=0;b<Date.abbrMonthNames.length;b++)if(Date.abbrMonthNames[b]==j)break;e.setMonth(b)}else e.setMonth(Number(a.substr(d.indexOf("mm"),2))-1);b=d.indexOf("yyyy");b>-1?(f<b&&(b+=h),e.setFullYear(Number(a.substr(b,4)))):e.setFullYear(Number(Date.fullYearStart+a.substr(d.indexOf("yy"),2)));d=d.indexOf("dd");
f<d&&(d+=h);e.setDate(Number(a.substr(d,2)));return isNaN(e.getTime())?false:e};var c=function(a){a="0"+a;return a.substring(a.length-2)}})();
function isDate(a){try{var a=a.replace(/-/g,"/").replace(/\./g,"/"),c=a.split("/"),a=true;c[2].length==1||c[2].length==2||(a=false);if(a&&!(c[1].length==1||c[1].length==2))a=false;a&&c[0].length!=4&&(a=false);if(a){var i=parseInt(c[2],10),g=parseInt(c[1],10),d=parseInt(c[0],10);if(a=d>1900&&d<=(new Date).getFullYear())if(a=g<=12&&g>0)a=g==2?d%4==0&&d%100!=0||d%400==0?i<=29:i<=28:g==4||g==6||g==9||g==11?i>0&&i<=30:i>0&&i<=31}return a}catch(e){return false}}String.prototype.isDate=function(){return isDate(this)};
jQuery(function(a){a.fn.listbuilder=function(c){function i(b){return a('<li class="listbuilder-entry"><span class="listbuilder-entry-text">'+b+'</span><a href="#" class="listbuilder-entry-remove" title="Remove '+b+' from the list." role="button"></a></li>').hover(function(){a(this).addClass("listbuilder-entry-hover")},function(){a(this).removeClass("listbuilder-entry-hover")}).attr("unselectable","on").css("MozUserSelect","none")}function g(){f.empty();a.each(e.val().split(h.delimChar),function(){this!=
""&&f.append(i(stripValue(this)))});f.append('<li class="listbuilder-entry-add"><input type="text" value="" title="'+h.userDirections+'" /></li>')}function d(){taval=[];f.find("span.listbuilder-entry-text").each(function(){taval.push(stripValue(a(this).text()))});taval.push(stripValue(f.find("input").val()));e.val(taval.join("\n"))}a("body").is("[role]")||a("body").attr("role","application");var e=a(this),h=a.extend({delimChar:/[,\n]/,width:e.width(),height:e.height(),completeChars:[188,13],userDirections:"To add an item to this list, type a name and press enter or comma.",
labelReplacement:false},c),f=a('<ul class="listbuilder"></ul>').width(h.width).height(h.height);window.stripValue=function(a){function b(a){return a>="a"&&a<="z"||a>="A"&&a<="Z"}function d(a){myCharCode=a.charCodeAt(0);return myCharCode>47&&myCharCode<58?true:false}for(var c="",f=0,e=a.length;f<e;f++)if(b(a.charAt(f))||d(a.charAt(f)))c+=a.charAt(f);console.log("strippedValue("+a+")="+c);return c};e.keyup(g);g();f.find("input").keydown(function(b){var d=a(this);a.each(h.completeChars,function(){if(b.keyCode==
this&&d.val()!=""&&d.val()!=h.delimChar){var a=d.val().split(h.delimChar)[0];d.parent().before(i(stripValue(a)));d.val("")}b.keyCode==this&&b.preventDefault()});var c=d.parent().prev();d.val()==""&&b.keyCode==8?(b.stopPropagation(),c.is(".listbuilder-entry-selected")?c.remove():c.addClass("listbuilder-entry-selected")):c.removeClass("listbuilder-entry-selected")}).keyup(function(){d();var b=a('<span style="visibility: hidden; position: absolute; left: -9999px;">'+a(this).val()+"</span>").css("font-size",
a(this).css("font-size")).appendTo("body");a(this).width(b.width()+20);b.remove()});a(document).click(function(){f.find(".listbuilder-entry-selected").removeClass("listbuilder-entry-selected");f.removeClass("listbuilder-focus")}).keydown(function(a){a.keyCode==8&&(f.find(".listbuilder-entry-selected").remove(),d())});f.click(function(b){a(this).addClass("listbuilder-focus");var c=a(b.target);c.is("a.listbuilder-entry-remove")?(c.parent().remove(),d()):c.is("li.listbuilder-entry, span")?(c.is("span")&&
(c=c.parent()),!b.shiftKey&&!b.ctrlKey&&!b.metaKey&&f.find(".listbuilder-entry-selected").removeClass("listbuilder-entry-selected"),(b.shiftKey||b.ctrlKey||b.metaKey)&&c.is(".listbuilder-entry-selected")?c.removeClass("listbuilder-entry-selected"):c.addClass("listbuilder-entry-selected")):(a(this).find(".listbuilder-entry-selected").removeClass("listbuilder-entry-selected"),f.find("input").eq(0).focus());return false});f.add("input").focus(function(){a(this).addClass("listbuilder-input-focus");f.addClass("listbuilder-focus")}).blur(function(){a(this).removeClass("listbuilder-input-focus");
f.removeClass("listbuilder-focus")});f.insertAfter(e);c=a("label[for="+e.attr("id")+"]");if(c.length&&h.labelReplacement){var b=a(h.labelReplacement);c.replaceWith(b);b.text(c.html())}return this}});
var dateFormat=function(){var a=/d{1,4}|m{1,4}|yy(?:yy)?|([HhMsTt])\1?|[LloSZ]|"[^"]*"|'[^']*'/g,c=/\b(?:[PMCEA][SDP]T|(?:Pacific|Mountain|Central|Eastern|Atlantic) (?:Standard|Daylight|Prevailing) Time|(?:GMT|UTC)(?:[-+]\d{4})?)\b/g,i=/[^-+\dA-Z]/g,g=function(a,c){a=String(a);for(c=c||2;a.length<c;)a="0"+a;return a};return function(d,e,h){var f=dateFormat;arguments.length==1&&Object.prototype.toString.call(d)=="[object String]"&&!/\d/.test(d)&&(e=d,d=void 0);d=d?new Date(d):new Date;if(isNaN(d))throw SyntaxError("invalid date");
e=String(f.masks[e]||e||f.masks["default"]);e.slice(0,4)=="UTC:"&&(e=e.slice(4),h=true);var b=h?"getUTC":"get",j=d[b+"Date"](),y=d[b+"Day"](),m=d[b+"Month"](),A=d[b+"FullYear"](),k=d[b+"Hours"](),l=d[b+"Minutes"](),z=d[b+"Seconds"](),b=d[b+"Milliseconds"](),v=h?0:d.getTimezoneOffset(),p={d:j,dd:g(j),ddd:f.i18n.dayNames[y],dddd:f.i18n.dayNames[y+7],m:m+1,mm:g(m+1),mmm:f.i18n.monthNames[m],mmmm:f.i18n.monthNames[m+12],yy:String(A).slice(2),yyyy:A,h:k%12||12,hh:g(k%12||12),H:k,HH:g(k),M:l,MM:g(l),s:z,
ss:g(z),l:g(b,3),L:g(b>99?Math.round(b/10):b),t:k<12?"a":"p",tt:k<12?"am":"pm",T:k<12?"A":"P",TT:k<12?"AM":"PM",Z:h?"UTC":(String(d).match(c)||[""]).pop().replace(i,""),o:(v>0?"-":"+")+g(Math.floor(Math.abs(v)/60)*100+Math.abs(v)%60,4),S:["th","st","nd","rd"][j%10>3?0:(j%100-j%10!=10)*j%10]};return e.replace(a,function(a){return a in p?p[a]:a.slice(1,a.length-1)})}}();
dateFormat.masks={"default":"ddd mmm dd yyyy HH:MM:ss",shortDate:"m/d/yy",mediumDate:"mmm d, yyyy",longDate:"mmmm d, yyyy",fullDate:"dddd, mmmm d, yyyy",shortTime:"h:MM TT",mediumTime:"h:MM:ss TT",longTime:"h:MM:ss TT Z",isoDate:"yyyy-mm-dd",isoTime:"HH:MM:ss",isoDateTime:"yyyy-mm-dd'T'HH:MM:ss",isoUtcDateTime:"UTC:yyyy-mm-dd'T'HH:MM:ss'Z'"};dateFormat.i18n={dayNames:"Sun,Mon,Tue,Wed,Thu,Fri,Sat,Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),monthNames:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,January,February,March,April,May,June,July,August,September,October,November,December".split(",")};
Date.prototype.formatDate=function(a,c){return dateFormat(this,a,c)};
jQuery(function(a){a.datepicker.regional.fr={closeText:"Fermer",prevText:"Pr\u00e9c\u00e9dent",nextText:"Suivant",currentText:"Aujourd'hui",monthNames:"Janvier,F\u00e9vrier,Mars,Avril,Mai,Juin,Juillet,Ao\u00fbt,Septembre,Octobre,Novembre,D\u00e9cembre".split(","),monthNamesShort:"Janv.,F\u00e9vr.,Mars,Avril,Mai,Juin,Juil.,Ao\u00fbt,Sept.,Oct.,Nov.,D\u00e9c.".split(","),dayNames:"Dimanche,Lundi,Mardi,Mercredi,Jeudi,Vendredi,Samedi".split(","),dayNamesShort:"Dim.,Lun.,Mar.,Mer.,Jeu.,Ven.,Sam.".split(","),
dayNamesMin:"D,L,M,M,J,V,S".split(","),weekHeader:"Sem.",dateFormat:"dd/mm/yy",firstDay:1,isRTL:false,showMonthAfterYear:false,yearSuffix:""};a.datepicker.setDefaults(a.datepicker.regional.fr)});
jQuery(function(a){function c(b){a(".date-pick").datepicker("destroy");a(".date-pick").datepicker({changeMonth:true,numberOfMonths:3,changeYear:true,showWeek:true,maxDate:(new Date).asString(),dateFormat:Date.format,onSelect:function(b,c){var d=this.id=="StartDate"?"minDate":"maxDate",f=this.id=="StartDate"?f:-f;if(b){var e=a.datepicker.parseDate(c.settings.dateFormat||a.datepicker._defaults.dateFormat,b,c.settings);a(".date-pick").not(this).datepicker("option",d,e.addDays(f).asString())}}});a("#StartDate").datepicker("option",
"maxDate",String(-b))}function i(b,c){window.clearTimeout(window.validationTimeout);var d=a("#msg");d.html('<div class="error"><span class="icon"></span><span>'+c+"</span></div>").slideDown();window.validationTimeout=window.setTimeout(function(){d.slideUp().empty()},7E3);b&&window.setTimeout(function(){b.focus()},400);console.log(c);return false}function g(){return parseInt(a("#DisplayType").val())}function d(b){function c(a){return a.charAt(0).toUpperCase()+a.substring(1).toLowerCase()}window.generatedOne=
true;setTimeout(function(){a("li",f).each(function(){var b=a(this).index(a(this).parent());f.wijtabs("remove",b)})},0);var d=0,m=0,h=g(),k=a("#StartDate").datepicker("getDate"),l=a("#EndDate").datepicker("getDate");a.when.apply(a,a.map(function(){var b,c=a("#Keywords").val();b=c!=null?c.trim():"";if(b=="")return[];c=[];b=b.split(/[,\n]/);for(var d=0,f=b.length;d<f;d++){var e=window.stripValue(b[d]!=null?b[d].trim():"");e!=""&&c.push(e)}return c}(),function(b){setTimeout(function(){var d={action:"generate_table",
StartDate:encodeURIComponent(k),EndDate:encodeURIComponent(l),Keyword:encodeURIComponent(b)},d=ajaxurl+"?"+a.param(d);f.wijtabs("add",d+"#recensements-table-tab-"+b,c(b))},0);return a.ajax({url:ajaxurl,dataType:"json",parseError:true,data:{action:"generate_series",DisplayType:encodeURIComponent(h),StartDate:encodeURIComponent(k),EndDate:encodeURIComponent(l),Keyword:encodeURIComponent(b)}})})).done(function(){function f(a,b){return"De "+dateFormat(a,dateFormat.masks.isoDate)+" \u00e0 "+dateFormat(b,
dateFormat.masks.isoDate)}function i(a,b){return"Janvier,F\u00e9vrier,Mars,Avril,Mai,Juin,Juillet,Ao\u00fbt,Septembre,Octobre,Novembre,Decembre".split(",")[b]+", "+a}function p(b){function e(b){return a.map(b,function(a){t[a.PostDate]=true;return Number(a.Posts)})}function g(b){return a.map(b,function(a){t[f(new Date(a.WeekStart),new Date(a.WeekEnd))]=true;return Number(a.Posts)})}function k(b){return a.map(b,function(a){t[i(a.Year,a.Month)]=true;return Number(a.Posts)})}console.assert(b.Success===
true,"Success should be true");var n=0,o=parseInt(b.TotalPosts);s<o&&(s=o);(function(b){a.each(b,function(){var a=parseInt(this.Posts);a>m&&(m=a);n+=a});d+=n})(b.Result);var l=null;if(h==1)l=e(b.Result);else if(h==2)l=g(b.Result);else if(h==3)l=k(b.Result);else throw Error("Unknown display type");l.length==0?(q=q||[],q.push(l),r=r||[],r.push({label:"<b>"+c(b.Keyword)+"</b> (<em>"+n+"</em> "+(n>1?"mentionnes":"mention")+" dans <em>"+o+"</em> "+(o>1?"articles":"article")+")"})):(w.push(l),u.push({label:"<b>"+
c(b.Keyword)+"</b> (<em>"+n+"</em> "+(n>1?"mentionnes":"mention")+" dans <em>"+o+"</em> "+(o>1?"articles":"article")+")"}))}a.lastPlot&&a.lastPlot.destroy();var s=0,w=[],u=[],q=null,r=null,t=function(){switch(g()){case 3:for(var a=new Date(k),b=new Date(l),c={},d=a.getFullYear(),e=b.getFullYear();d<=e;d++)for(var j=a.getMonth(),h=b.getMonth();j<=h;j++)c[i(d,j)]=false;return c;case 2:e=new Date(k);a=new Date(l);b={};c=e.getDay()==0?new Date(e.getTime()):new Date(e.getTime()+(1-(e.getDay()+1))*864E5);
for(e=e.getDay()==6?new Date(e.getTime()):new Date(e.getTime()+(7-(e.getDay()+1))*864E5);c.getTime()<=a.getTime();c.addDays(7),e.addDays(7))b[f(c,e)]=false;return b}return{}}(),x=a.makeArray(arguments);a.isArray(x[0])?a.each(x,function(){p(this[0])}):p(x[0]);q&&a.each(q,function(){w.push(this)});r&&a.each(r,function(){u.push(this)});u.push({lineWidth:4,markerOptions:{style:"square"}});a.lastPlot=a.jqplot("recensements-graph",w,{title:"Recensements des mots-cl\u00e9s (<em>"+d+"</em> "+(d>1?"mentionnes":
"mention")+" dans <em>"+s+"</em> "+(s>1?"articles":"article")+" aux totales)",seriesDefaults:{renderer:a.jqplot.BarRenderer,pointLabels:{show:true},rendererOptions:{barPadding:10,barMargin:10,barWidth:10}},series:u,axes:{xaxis:{renderer:a.jqplot.CategoryAxisRenderer,rendererOptions:{tickRenderer:a.jqplot.CanvasAxisTickRenderer},tickOptions:{fontSize:"10pt",fontFamily:"Tahoma",angle:-40,fontWeight:"normal",fontStretch:1},ticks:a.map(t,function(a,b){return a&&b||null})},yaxis:{autoscale:true,tickOptions:{formatString:"%d"},
min:0,max:(m>8?m:8)+6,tickInterval:1}},legend:{show:true,placement:"inside",location:"ne"},noDataIndicator:{show:true,indicator:"Il n'y pas des donn\u00e9es",axes:{xaxis:{min:0,max:5,tickInterval:1,showTicks:false},yaxis:{min:0,max:8,tickInterval:2,showTicks:false}}}});a(".collapsible").find("legend").find("h2").text("Modifier les Param\u00e8tres");a("#generate_report_submit").val("R\u00e9g\u00e9n\u00e9rer le graphe");e(a(".collapsible"));b()}).fail(function(a){i(null,a.Result.Msg);b()})}function e(b){if(a(b).is(".collapsed")){var c=
a("> div:not(.action)",b);a(b).removeClass("collapsed");c.hide();c.slideDown({duration:"slow",easing:"linear",complete:function(){h(this.parentNode);this.parentNode.animating=false;a("div.action",b).show()},step:function(){h(this.parentNode)}})}else a("div.action",b).hide(),c=a("> div:not(.action)",b).slideUp("slow",function(){a(this.parentNode).addClass("collapsed");this.parentNode.animating=false})}function h(b){var c=self.innerHeight||document.documentElement.clientHeight||a("body")[0].clientHeight||
0,d=self.pageYOffset||document.documentElement.scrollTop||a("body")[0].scrollTop||0,e=a(b).offset().top;e+b.offsetHeight+55>c+d&&(b.offsetHeight>c?window.scrollTo(0,e):window.scrollTo(0,e+b.offsetHeight-c+55))}a.jqplot.config.enablePlugins=true;window.generatedOne=false;a.fn.enable=function(a){a===void 0&&(a=true);return this.each(function(){this.disabled=!a})};a.fn.doBusy=function(b){a('<span id="loading"></span>').insertBefore(this);this.enable(false);var c=this;b(function(){c.enable();c.parent().find("#loading").remove()})};
a.ajaxPrefilter(function(b,c,d){if(b.parseError)a.Deferred(function(b){d.done(b.resolve).fail(function(c,d,e){c.statusCode()==500?b.rejectWith(this,[c,d,e]):b.rejectWith(this,[a.parseJSON(c.responseText),"success",c])})}).promise(d),d.success=d.done,d.error=d.fail});(function(b){a("fieldset.collapsible > legend:not(.collapsible-processed)",b).each(function(){var b=a(this.parentNode);a("input.error, textarea.error, select.error",b).size()>0&&b.removeClass("collapsed");var c=this.innerHTML;a(this).empty().append(a('<a href="#">'+
c+"</a>").click(function(){var b=a(this).parents("fieldset:first")[0];if(!b.animating)b.animating=true,e(b);return false})).after(a('<div class="fieldset-wrapper"></div>').append(b.children(":not(legend):not(.action)"))).addClass("collapsible-processed")})})(this);var f=a("#recensements-table").wijtabs({tabTemplate:'<li><a href="#{href}">#{label} </a> </li>',spinner:'<em class="loading">Chargement de contenu...</em>',add:function(b,c){a(c.panel).html('<div class="loading"></div>');setTimeout(function(){a("table",
c.panel).tablesorter({widthFixed:true,locale:"en",widgets:["zebra"],headers:{0:{sorter:true},1:{sorter:false},2:{sorter:false},3:{sorter:false}}})},100)},show:function(){},alignment:"top",scrollable:true});Date.firstDayOfWeek=0;Date.format="yy-mm-dd";c(1);(function(){function b(b,c){var d=a("#"+b),e=d.val(),e=e!=null?e.trim():"";return e==""?i(d,c):true}window.isStartDateValid=function(){return b("StartDate","La date de d\u00e9but est necessaire")&&(a("#StartDate").val().isDate()||i(a("#StartDate"),
"La date de d\u00e9but est invalide"))};window.isEndDateValid=function(){return b("EndDate","La date de fin est necessaire")&&(a("#EndDate").val().isDate()||i(a("#EndDate"),"La date de fin est invalide"))};window.isKeywordsValid=function(){var c;if(c=b("Keywords","Il faut au moins un mot-cl\u00e9"))a(".listbuilder").find("input").eq(0).focus(),c=true;return c}})();a("#Keywords").listbuilder({width:"90%",height:"150px",labelReplacement:'<label for="Keywords"></label>'});a("#DisplayType").change(function(){switch(g()){case 3:c(30);
break;case 2:c(7);break;default:c(1)}window.generatedOne&&window.isStartDateValid()&&window.isEndDateValid()&&window.isKeywordsValid()&&a("#generate_report_submit").doBusy(d)});a("#report_form").submit(function(){window.isStartDateValid()&&window.isEndDateValid()&&window.isKeywordsValid()&&a("#generate_report_submit").doBusy(d);return false})});